apiVersion: "v1"
kind: Pod
metadata:
  name: pv-extract
spec:
  containers:
    - name: pv-extract-pod
      image: registry.access.redhat.com/ubi8/ubi
      command: ["sleep", "3000"]
      volumeMounts:
      - mountPath: "/scan-results"
        name: scan-vol
  volumes:
    - name: scan-vol
      persistentVolumeClaim:
        claimName: <scan results pvc>